name: Context

on: 
    workflow_dispatch: 

jobs:
    print-context:
        runs-on: ubuntu-latest
        steps:
            - name: echo context of github
              env:
                  GITHUB_CONTEXT: ${{toJson(github)}}
              run: echo "$GITHUB_CONTEXT"