name: action-worlfow

on: 
    push:
        branches: main
env:
  TEST_NAME: ${{ vars.TEST_NAME }}

jobs:
    first:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4  

            - name: list files
              run: |
                ls -ltra
                echo "This is executing"
                cat .github/workflows/first-action.yml
                echo " My name is $TEST_NAME"
              