name: action-worlfow

on: 
    push:
        branches: main

jobs:
    first:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@4  

            - name: list files
              run: |
                ls -ltra
                echo "This is executing"
                cat /.github/workflows/first-action.yml
              