name: Executing Shell script

on: 
    workflow_dispatch: 

jobs:
    shell-execute:
        runs-on: ubuntu-latest
        steps:
            - name: checout repo
              uses: actions/checkout@v4

            - name: execute shell
              run: |
                ls -ltra
                chmod +x .github/workflows/test.sh
                .github/workflows/test.sh