name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: actions
    outputs:
      message: ${{ steps.results.outputs.result }}

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        id: results
        run: echo "result=Build and test complete!" >> $GITHUB_OUTPUT

  next-build:
    needs: build
    runs-on: ubuntu-latest
    environment: actions
    steps:
      - name: Use output from build job
        run: echo "The build job said'${{ needs.build.outputs.message }}'"

      - name: calling ENV
        run: echo "Hi my Name is $NAME"
      - name: Print env vars
        run: env

